[package]
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
description = "Atomic polyfills, for targets where they're not available."
edition = "2018"
license = "MIT OR Apache-2.0"
name = "atomic-polyfill"
readme = "README.md"
repository = "https://github.com/embassy-rs/atomic-polyfill"
version = "0.1.3"

categories = [
  "embedded",
  "no-std",
  "concurrency",
]

[target.thumbv6m-none-eabi.dependencies]
cortex-m = {version = "0.7.1"}

[target.riscv32imc-unknown-none-elf.dependencies]
riscv = {version = "0.7.0"}
